db:
  image: mysql:5.7
  environment: 
    MYSQL_ROOT_PASSWORD: mypassword
    MYSQL_USER: user1
    MYSQL_PASSWORD: pass1
web:
  build: .
  environment:
    JDBC_URL: jdbc:mysql://db:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    JDBC_USER: user1
    JDBC_PASS: pass1
  command: /usr/local/tomcat/bin/catalina.sh run
  
  ports:
    - "80:8080"
  links:
    - db